import React from "react";

class DealerPolicy extends React.Component {
  render() {
    return (
      <div>
        
        <div className="container" style={{ marginTop: "50px" }}>
          <h1 style={{ textAlign: "center" }}>Privacy Policy for sec2hand dealer</h1>
          This document is an electronic record in terms of Information
          Technology Act, 2000 and the amended provisions pertaining to
          electronic records in various statutes as amended by the Information
          Technology Act, 2000. This electronic record is generated by a
          computer system and does not require any physical or digital
          signatures. Welcome to SEC2HAND. If you continue to browse and use the
          Website / App (hereinafter, collectively referred to as "platform")
          you are agreeing to comply with and be bound by the following terms
          and conditions of use, including any future amendments (“Terms and
          conditions”), which together with our Privacy Policy govern our
          relationship with you in relation to this Website / App (“Agreement”)
          GENERAL For the purpose of the User Agreement, Registered User / and
          wherever the context so require 'You' shall mean any natural or legal
          person who has agreed to become a member of the Website by providing
          Registration Data (as defined hereinafter) while registering on the
          using the computer systems of the Website and accepted this electronic
          version / electronic record of the User Agreement and has allocated
          himself a unique identification user name ("User ID" and
          "Password").As a new Registered User, this User Agreement shall be
          effective and binding upon your 'acceptance'. 'Acceptance' shall mean
          your affirmative action in clicking on 'check box' and on the
          'continue button' as provided on the registration page. If you do not
          agree or are not willing to be bound by the terms and conditions of
          this User Agreement, please do not click on the "check box" and on the
          "Continue" button and do not seek to obtain access to or otherwise use
          the Website.* You may not modify copy, distribute, transmit, display,
          perform, reproduce, publish, license, create derivative works from,
          transfer, or sell any information, software, products or services
          obtained from the Website.* As a condition of your use of the
          “Website”, you pledge that you will not use the site for any purpose
          that is unlawful or prohibited by these terms, conditions, and
          notices. You may not use the Website in any manner which could damage,
          disable, overburden, impair, or interfere with any other party's use
          and enjoyment of the Website. You may not obtain or attempt to obtain
          any materials or information through any means not intentionally made
          available or provided for through the Website. You agree, and are
          hereby put on notice, that you are prohibited from posting or
          transmitting to or from this Website any unlawful, threatening,
          libelous, defamatory, inflammatory, pornographic, or profane material
          or any other material that could give rise to any civil or criminal
          liability under law. You are solely responsible for the content of any
          comments you make. AMENDMENTS SEC2HAND BUSINESS SOLUTIONS PVT. LTD
          (hereinafter mentioned as SEC2HAND)’s may amend this User Agreement
          and/or the SEC2HAND Privacy Policy at any time by posting a revised
          version on the Website / Mobile App. All updates and amendments shall
          be notified to You via SEC2HAND Website/Mobile App Announcement Board.
          The revised version will be effective at the time SEC2HAND posts it on
          the Website / Mobile App.You are advised to regularly check for any
          amendments or updates to the terms and conditions contained in this
          User Agreement and in the SEC2HAND Website/Mobile App Privacy Policy.
          MEMBERSHIP ELIGIBILITY Use of the Website is available only to persons
          who can form legally binding contracts under Indian Contract Act,
          1872. Persons who are "incompetent to contract" within the meaning of
          the Indian Contract Act, 1872 including minors, un-discharged
          insolvents etc. are not eligible to use the Website/Mobile App. If you
          are a minor i.e. under the age of 18 years, you shall not register as
          a member of the Website. SEC2HAND or its affiliates reserves the right
          to terminate your membership and refuse to provide you with access to
          the Website if it is brought to or its affiliates notice or if it is
          discovered that you are under the age of 18 years .BUSINESS ENTITY
          REGISTRATION If you are registering as a business entity, you
          represent that you are duly authorised by the business entity to
          accept this User Agreement and you have the authority to bind that
          business entity to this User Agreement and Privacy Policy. If you use
          our Website/Mobile App, you shall be solely responsible for
          maintaining the confidentiality of your account credentials and you
          agree to accept responsibility for all activities occurring under your
          account. If at any point feel that your account credentials may have
          been compromised, please bring it to our attention immediately. You
          agree to provide us true, accurate, current and complete information
          about yourself as required at the time of your registration and
          promptly update us in the event of any change in the information
          provided. You agree to maintain only one active account with us,
          accessing our Website/Mobile App through multiple accounts may result
          in termination of all your accounts. You hereby unconditionally allow
          us and our service providers to contact you via text messages or by
          phone calls and agree that you shall have no claim against us or our
          service providers under any applicable law in relation to such
          communication. YOUR ACCOUNT AND REGISTRATION OBLIGATIONS If you use
          the Website/Mobile App, you are responsible for maintaining the
          confidentiality of your User ID and Password and for restricting
          access to your Mobile device, computer, computer system and computer
          network, Mobile carrier network and you are responsible for all
          activities that occur under your User ID and Password. In addition,
          you agree to provide true, accurate, current and complete information
          into the Website/ Mobile application. ELECTRONIC COMMUNICATION When
          You use the Website /Mobile App, You agree and understand that You are
          communicating with SEC2HAND through electronic records and You consent
          to receive communications via electronic records from SEC2HAND
          periodically and as and when required. SEC2HAND will communicate with
          You by email or by an update in privacy policy/user agreement/terms
          and conditions notice or electronic records on the SEC2HAND Website
          /Mobile App which will be deemed adequate service of notice /
          electronic record .FEES AND SERVICES Membership on the Website is
          available on the payment of prescribed fee structure and meeting other
          conditions as described in the User Agreement. All fees are
          non-refundable. SEC2HAND may at its sole discretion introduce new
          services and modify some or all of the existing services offered on
          the Website /Mobile App. In such an event SEC2HAND reserves the right
          to introduce fees for the new services offered or amend/introduce fees
          for existing services, as the case may be. Non-payment: SEC2HAND
          reserves the right to issue a warning, temporarily /indefinitely
          suspend or terminate your membership of the Website /Mobile App and
          refuse to provide you with access to the Website /Mobile App in case
          of non-payment of fees by You to SEC2HAND, SEC2HAND also reserves the
          right to take legal action in case of non-payment of fees by You to
          SEC2HAND. Unless otherwise stated, all fees shall be quoted in Indian
          Rupees (INR) TAXES You are responsible for paying all fees associated
          with the use of the Website /Mobile App and you agree to bear any and
          all applicable taxes, charges, cesses etc. levied thereon. USE OF THE
          WEBSITE AND MOBILE APPLICATION You understand and agree that SEC2HAND
          and the Website /Mobile App merely provides services to its Registered
          Users. All items advertised / listed and the contents therein are
          advertised and listed are third party user generated contents.
          SEC2HAND neither initiates the transmission nor selects the sender and
          receiver of the transmission nor selects nor modify the information
          contained in the transmission. The Website /Mobile App is a tool that
          provides you the means to list new/used motorized transport vehicles
          (Vehicles), products and services for sale. It is an online platform
          for listing classified advertisements for sale of Vehicles, products
          and services which brings together potential buyers and sellers
          through the internet. The Website /Mobile App is not a party to
          transactions between buyers and sellers originating on or through it.
          The Website /Mobile App merely provides infrastructure which is used
          by users for posting classified advertisements. The Website /Mobile
          App does not initiate or select the receiver of information
          transmitted by users using its network, nor does it select or modify
          information contained in such transmissions. For this reason, the
          Platform acts as a meIre conduit or an internet intermediary, and has
          no liability in connection with third party content available on the
          Website /Mobile App or any transactions between third parties pursuant
          to such content. Some of our features may enable the displaying of
          your advertisement on platforms other than the Website /Mobile App. By
          posting an advertisement through us, you agree that your
          advertisements can be displayed on these other sites. The display of
          your advertisements on these sites will be governed by the terms of
          use and policies of such sites. SEC2HAND has no control over the third
          party user generated contents. You agree, undertake and confirm that
          your use of the Website /Mobile App shall be strictly governed by the
          following binding principles: "Your Information" is defined as any
          information you provide on the Website /Mobile App. You are solely
          responsible for Your Information, and we act only as a passive conduit
          for your online distribution and publication of Your Information. Your
          Information (or any items listed) : * shall not be false, inaccurate
          or misleading;* shall not be fraudulent or involve the sale of
          counterfeit or stolen items;* shall not infringe any third party's
          intellectual property, trade secret or other proprietary rights or
          rights of publicity or privacy;* shall not, directly or indirectly,
          offer, attempt to offer, trade or attempt to trade in any item, the
          dealing of which is prohibited or restricted in any manner under the
          provisions of any applicable law, rule, regulation or guideline for
          the time being in force. Without prejudice to the generality of the
          above, SEC2HAND does not permit transactions in the following items
          including but not limited to categories as stated in this document.*
          shall not contain any viruses, Trojan horses, worms, time bombs,
          cancelbots, easter eggs or other computer programming routines that
          may damage, detrimentally interfere with, diminish value of,
          surreptitiously intercept or expropriate any system, data or personal
          information;* shall not create liability for us or cause us to lose
          (in whole or in part) the services of our ISPs or other suppliers; and
          Solely to enable SEC2HAND to use the information you supply us with,
          so that we are not violating any rights you might have in Your
          Information, you agree to grant us a non-exclusive, worldwide,
          perpetual, irrevocable, royalty-free, sub-licensable (through multiple
          tiers) right to exercise the copyright, publicity, and database rights
          (but no other rights) you have in Your Information, in any media now
          known or not currently known, with respect to Your Information.
          SEC2HAND will only use Your Information in accordance with this
          Agreement. In the event that any transaction, attempted transaction or
          information relating to any item, goods or service which is in
          violation of this User Agreement or applicable law comes to your
          knowledge, you shall take all steps to inform SEC2HAND of the same.
          You may contact SEC2HAND from Contact Us.You shall comply with all
          applicable Domestic laws, rules and regulations (including the
          provisions of any applicable Exchange Control Laws or Regulations in
          Force) and International Laws, Foreign Exchange Laws, Statutes,
          Ordinances and Regulations (including, but not limited to Goods and
          Service Tax and any other applicable laws) regarding your use of the
          Website /Mobile App. You shall not engage in any transaction in an
          item or service, which is prohibited by the provisions of any
          applicable law including exchange control laws or regulations for the
          time being in force.From time to time, you shall be responsible for
          providing information relating to the items or services. In this
          connection, you undertake that all such information shall be accurate
          in all respects. You shall not exaggerate or over emphasize the
          attributes of such items or services so as to mislead other Users in
          any manner. You shall not attempt to or circumvent or manipulate our
          Fee structure, the billing process or Fees owed to SEC2HAND. PLATFORM
          AND COMMUNICATION SEC2HAND is not and cannot be a party to or control
          in any manner any interaction between two Users of the Website or any
          other third party. Consequently:* SEC2HAND does not make any
          representation or Warranty as to the attributes (such as quality,
          worth, marketability, etc.) of the items or services on the Website.
          SEC2HAND accepts no liability for any errors or omissions, whether on
          behalf of itself or third parties.* SEC2HAND does not make any
          representation or warranty as to the attributes (such as legal title,
          creditworthiness, identity, etc.) of any information on the Website.
          You are advised to independently verify the bona fides of any
          particular User that you choose to deal with on the Website/Mobile
          Application and use your best judgment in that behalf.* SEC2HAND is
          only providing a platform for communication and it is agreed that the
          contract for sale of any of the products or services shall be a
          strictly bipartite contract between the two parties. At no time shall
          any right, title or interest over the items vest with SEC2HAND nor
          shall SEC2HAND have any obligations or liabilities in respect of such
          contract. SEC2HAND is not responsible for unsatisfactory or delayed
          performance of services or damages or delays as a result of items
          which are out of stock, back ordered or otherwise unavailable. At no
          time shall any right, title or interest over the items vest with
          SEC2HAND nor shall SEC2HAND have any obligations or liabilities in
          respect of such contract. SEC2HAND is not responsible for
          unsatisfactory or delayed performance of services or damages or
          delays. BREACH You acknowledge and agree that you are solely
          responsible for your content posted on, transmitted through, or linked
          from our Services (“Content”) and the consequences of posting,
          transmitting, linking or publishing it. You affirm, acknowledge,
          represent, warrant and covenant that: (i) you own or have and shall
          continue to, for such time the Content is available on the Platform,
          have the necessary licenses, rights, consents, and permissions to use
          such Content on the Website/Mobile Application (including without
          limitation all patent, trademark, trade secret, copyright or other
          proprietary rights in and to any and all such Content) and authorize
          us to use such Content to enable inclusion and use of the Content in
          the manner contemplated by these Terms; (ii) you have the written
          consent, release, and/or permission of each and every identifiable
          individual person or business in the Content to use the name or
          likeness of each and every such identifiable individual person or
          business to enable inclusion and use of the Content in the manner
          contemplated by these Terms. You retain all of your ownership rights
          in your Content, however, by submitting any Content on the Platform
          you grant: •us an irrevocable, perpetual, worldwide, non-exclusive,
          royalty-free, sub-licensable, transferable license to use, reproduce,
          distribute, prepare derivative works of, display, and perform the
          Content in connection with the Platform and our (and our successors')
          business, including without limitation for the purpose of promoting
          and redistributing part or all of the Website/Mobile Application and
          the Content therein (and derivative works thereof) in any media
          formats and through any media channels now or hereafter known; •us all
          rights necessary to prohibit or allow any subsequent aggregation,
          display, copying, duplication, reproduction, or exploitation of the
          Content on the Services or the Website/Mobile Application by any party
          for any purpose; and •each user of the Website/Mobile Application a
          non-exclusive license to access the Content through the Website/Mobile
          Application. This license to each user granted by you terminates once
          you or we remove or delete such Content from the Website/Mobile
          Application. You agree not to post, email, host, display, upload,
          modify, publish, transmit, update or share any information on the
          Website/Mobile Application, or otherwise make available any content:
          •that violates any law or regulation; •that is copyrighted or
          patented, protected by trade secret or trademark, or otherwise subject
          to third party proprietary rights, including privacy and publicity
          rights, unless you are the owner of such rights or have permission or
          a license from their rightful owner to post the material and to grant
          us all of the license rights granted in these Terms; •that infringes
          intellectual property rights of any party, or is content that you do
          not have a right to make available under any law, regulation,
          contractual or fiduciary relationship(s); •that is harmful, abusive,
          unlawful, threatening, harassing, blasphemous, defamatory, obscene,
          pornographic, paedophilic, libellous, invasive of another's privacy or
          other rights, hateful, or racially, ethnically objectionable,
          disparaging, relating or encouraging money laundering or illegal
          gambling or harms or could harm minors in any way or otherwise
          unlawful in any manner whatsoever; •that includes personal or
          identifying information about another person without that person's
          explicit consent; •that impersonates any person or entity, including,
          but not limited to, any of our employees, or falsely states or
          otherwise misrepresents an affiliation with a person or entity;
          •deceives or misleads the addressee about the origin of such messages
          or communicates any information which is grossly offensive or menacing
          in nature; •that is false, deceptive, misleading, deceitful,
          misinformative, or constitutes "bait and switch" offer; •that
          constitutes or contains "pyramid schemes," "affiliate marketing,"
          "link referral code," "junk mail," "spam," "chain letters," or
          unsolicited advertisements of a commercial nature; •that includes
          links to commercial services or third party websites, except as
          specifically allowed by us; •that advertises any illegal services or
          the sale of any items the sale of which is prohibited or restricted by
          applicable law, including without limitation items the sale of which
          is prohibited or regulated by applicable law; •that contains software
          viruses or any other computer code, files or programs designed to
          interrupt, destroy or limit the functionality of any computer software
          or hardware or telecommunications equipment or any other computer
          resource; •that disrupts the normal flow of dialogue with an excessive
          number of messages (flooding attack) to the Services, or that
          otherwise negatively affects other users' ability to use the Services
          or the Platform; or •that employs misleading email addresses, or
          forged headers or otherwise manipulated identifiers in order to
          disguise the origin of content transmitted through the service. You
          agree not to: •contact anyone who has asked not to be contacted, or
          make unsolicited contact with anyone for any commercial purpose,
          specifically, contact any user to post advertisement on a third party
          website or post any advertisement on behalf of such user; or to
          "stalk" or otherwise harass anyone; •make any libellous or defamatory
          comments or postings to or against anyone; •collect personal data
          about other users or entities for commercial or unlawful purposes;
          •use automated means, including spiders, robots, crawlers, data mining
          tools, or the like to download or scrape data from the Services,
          except for internet search engines and non-commercial public archives
          that comply with our robots.txt file; •post content that is outside
          the local area or not relevant to the local area, repeatedly post the
          same or similar Content, or otherwise impose unreasonable or
          disproportionately large loads on our servers and other
          infrastructure; •attempt to gain unauthorized access to computer
          systems owned or controlled by us or engage in any activity that
          disrupts, diminishes the quality of, interferes with the performance
          of, or impairs the functionality of, our services; or •use any
          automated device or software that enables the submission of automatic
          postings on the Website/Mobile Application without human intervention
          or authorship (an "automated posting device"), including without
          limitation, the use of any such automated posting device in connection
          with bulk postings, or for automatic submission of postings at certain
          times or intervals. CONTENT REQUIREMENTS In relation to advertisements
          posted by you through our Services, you shall: •only post
          advertisements for the sale of new or used motorized transport
          vehicles, products and service’s advertisements relating to any other
          products or services are prohibited; •only post advertisement for sale
          of new or used Vehicle, products and services of which you have
          possession, legal documentation, ability to transfer title, and
          otherwise possess all legal requirements to effect sale of the new or
          used Vehicle, products and services; •submit correct and full
          information about the new or used Vehicle, products and services in
          the advertisement for sale; •ensure that the description of the new or
          used Vehicle, products and services is not misleading in any manner
          and describes the actual condition of the new or used Vehicle,
          products and services in the advertisement for sale; •ensure that the
          photographs uploaded by you in the advertisement relate to and are
          illustrative of, the new or used Vehicle, products and services for
          which the advertisement is being posted and do not contain any
          publicity material including contact details; •ensure that each
          advertisement or listing relates to sale of only one newor used
          Vehicle, products and service; •ensure that you do not post duplicate
          content, that is to say, more than one advertisement for sale of a new
          or used Vehicle, products and services; •ensure that you list the new
          or used Vehicle, products and services in the correct category on the
          Platform; and •not list advertisements solely for the purposes of
          generating leads or otherwise soliciting business; •ensure that all
          listed ne or used Vehicles, products and services are kept in stock
          for successful completion of sales or performance of service – in the
          event of sale of the new or used Vehicle, products and services on the
          Platform or by any other means, you shall immediately remove the
          relevant advertisement from the Platform; •not test the Platform with
          false purchase requests; and •ensure that you do not disclose your
          contact details like phone number, address, email address in the
          listing process, other than in the specified place in the listing
          form. Please report any violations of the Terms that you become aware
          of by contacting us. Our failure to act with respect to a breach by
          you or others does not waive our right to act with respect to
          subsequent or similar breaches by you or others. You agree that we
          may, under some circumstances and without prior notice to you,
          terminate your use of and access to any of the parts of the Platform
          without any liability whatsoever towards you. Some of the reasons for
          such termination may include, (a) your breach or suspected breach of
          these Terms or any contract entered with us; (b) a request by law
          enforcement or another government agency, (c) our decision to
          discontinue or change all or part of the Platform; (d) technical or
          security issues; and (e) any fraudulent or illegal activities. All
          terminations will be made in our sole discretion and you agree that we
          will not be liable for any termination of your use of or access to the
          Platform. Notwithstanding any other provision of these Terms, we
          retain the right to seek equitable remedies, including without
          limitation, specific performance of any term contained in these Terms,
          or a preliminary or permanent injunction against the breach or
          threatened breach of any such term or in aid of the exercise of any
          power granted in these Terms, or any combination thereof. Without
          limiting other remedies, SEC2HAND may limit your activity, immediately
          temporarily/indefinitely suspend or terminate your membership, and/or
          refuse to provide you with access to the Website in the event, but not
          limited to: * If you breach the User Agreement or the documents,
          agreements rules, policies, terms and conditions these incorporate by
          reference;* If SEC2HAND is unable to verify or authenticate any
          information you provide; or* If it is believed that your actions may
          cause legal liability for you, other Users or SEC2HAND* SEC2HAND may
          at any time at its sole discretion reinstate suspended Users. A User
          that has been indefinitely suspended may not register or attempt to
          register with SEC2HAND or use the Website/Mobile Application in any
          manner whatsoever until such time that such User is reinstated by
          SEC2HAND. Notwithstanding the foregoing, if you breach the User
          Agreement or the documents it incorporates by reference, SEC2HAND
          reserves the right to recover any amounts due and owing by you to
          SEC2HAND and to take strict legal action including but not limited to
          a referral to the appropriate police or other authorities for
          initiating criminal or other proceedings against you. NO WARRANTY
          SEC2HAND and its suppliers, affiliates and service providers provide
          the Website "as is" and without any Warranty or condition, express,
          implied or statutory and specifically disclaim any implied Warranties
          of title, merchantability, fitness for a particular purpose and
          non-infringement. You expressly agree that your use of the
          Website/Mobile Application is at your risk. LIMITATION OF LIABLITY In
          no event shall SEC2HAND or its suppliers, affiliates and service
          providers be liable for any direct, indirect, incidental, special,
          incidental, consequential or exemplary damages, including but not
          limited to, damages for loss of profits, goodwill, use, data or other
          intangible losses arising out of or in connection with the Website/
          Mobile Application, its services or this agreement (however arising,
          including negligence). SEC2HAND and Its associates and service
          providers and technology partners make no representations or
          Warranties about the accuracy, reliability, completeness, and/or
          timeliness of any content, information, software, text, graphics,
          links or communications provided on or through the use of the Website
          or that the operation of the Website or will be error free and/or
          uninterrupted. Consequently, SEC2HAND assumes no liability whatsoever
          for any monetary or other damage suffered by you on account of:* The
          delay, failure, interruption, or corruption of any data or other
          information transmitted in connection with use of the Website.* Any
          interruption or errors in the operation of the Website. You expressly
          understand and agree that SEC2HAND. shall not be liable for any
          direct, indirect, incidental, special, consequential or exemplary
          damages, including but not limited to, damages for loss of profits,
          goodwill, use, data or other intangible losses (even if SEC2HAND has
          been advised of the possibility of such damages).* The content,
          accuracy and reliability of the material provided by the other users
          or any other individual. PROPERTY RIGHTS The information contained in
          this Website including all images, illustrations, designs,
          photographs, video clips, writings and other materials that appear
          herein are copyrights, trademarks, trade dress or other intellectual
          property owned, controlled, or licensed (all of which, collectively,
          “Contents”) by the Website or its subsidiaries and affiliates or are
          the property of their respective owners. The name “SEC2HAND” and its
          logos are trademarks of the Website/Mobile Application.
          REPRESENTATIONS AND WARRANTIES OF THE SEC2HAND The Website/Mobile
          Application and/or its respective suppliers, affiliates, associates,
          representatives make no representations about the suitability,
          reliability, availability, timeliness and accuracy of the information,
          products and services contained on the Website/Mobile Application for
          any purpose. All such information, products offered, services offered
          etc. are provided on an "as is where is" basis without warranty of any
          kind. Website/Mobile Application and/or its respective suppliers,
          associates, affiliates hereby disclaim all warranties and conditions
          with regard to the information, products, services, including all
          implied warranties and conditions of merchantability, fitness for a
          particular purpose, title and non-infringement. Nor do they guarantee
          that this information will be error free or continuously available, or
          that the service will be free of viruses or other harmful components.
          The information generated by the Website/Mobile Application is
          believed to be accurate, but the Website/Mobile Application and its
          suppliers do not warrant or guarantee such accuracy. The
          Website/Mobile Application and its suppliers do not authorize the use
          of such information for any purpose other than your personal use, and
          prohibit to the maximum extent allowable the resale, redistribution,
          and use of this information for commercial purposes. In no event shall
          the Website/Mobile Application be liable for any direct, indirect,
          punitive, incidental, special, consequential damages or any damages
          whatsoever including without limitation, damages for loss of use
          arising out of or in any way connected with the use or performance of
          the Website/Mobile Application, with the delay or inability to use the
          Website/Mobile Application or related services, the provision or
          failure to provide services, or for any information, products,
          services and related graphics obtained through the Website/Mobile
          Application, or otherwise arising out of the use of the Website/Mobile
          Application, whether based on contract, tort, negligence, strict
          liability or otherwise, even if the Website/Mobile Application or any
          of its suppliers/affiliates has been advised of the possibility of
          damages. If you are dissatisfied with any portion of the
          Website/Mobile Application or with any of these terms of use, your
          sole and exclusive remedy is to discontinue using the Website/Mobile
          Application. The Website/Mobile Application shall not be responsible
          for, and does not guarantee the performance of, any goods or services
          purchased through the Website/Mobile Application REPRESENTATIONS AND
          WARRANTIES OF THE USERS You shall not upload from, post or transmit or
          distribute or otherwise publish through the Site any materials which:
          restrict any other user from using the Website/Mobile Application and
          /or are unlawful, threatening, abusive, defamatory, vulgar, offensive,
          pornographic, or indecent and /or constitute or contain false or
          misleading indications of origin or statements of fact. You further
          represents and warrants SEC2HAND that all the information provided by
          you about yourself are true and accurate; and you shall be responsible
          for all actions taken by you or by any other individual through your
          ID to whom you have given authorization to use. COPYRIGHT AND
          TRADEMARK Unless otherwise stated, copyright and all intellectual
          property rights in all material presented on the site including but
          not limited to text, graphics, button icons, images, audio clips,
          digital downloads, data compilations, and software, trademarks and
          logos appearing on the site are the property of the SEC2HAND, its
          parent and are protected under applicable Indian and international
          laws. You agree not to use any trademark or logo or other proprietary
          information of the SEC2HAND .COMMUNICATION You agree that SEC2HAND can
          and may communicate with you via phone calls, SMS, E-Mails and/or any
          other method & SEC2HAND will not be liable to you and/or any other
          authority for such an act. If your number is registered with any Do
          Not Call (DNC) and/or Do Not Disturb (DND) service you hereby
          authorize SEC2HAND to communicate with you via telephone calls, SMS,
          E-Mails and/or any other method and You will not in any case hold
          SEC2HAND liable for any communication in this regard INDEMNITY You
          shall indemnify and hold harmless SEC2HAND and (as applicable),
          subsidiaries, third-parties and their respective officers, directors,
          agents, employees, suppliers, service partners, agents and consultants
          from any claim or demand, or actions including reasonable attorneys'
          fees, made by any third party or penalty imposed due to or arising out
          of your breach of this Agreement, or the documents they incorporates
          by reference, or your violation of any law, rules or regulations or
          the rights of a third party. STORING OF USERS AND CUSTOMER’S DETAILS
          By using this website, you hereby legally authorised SEC2HAND under
          the applicable laws/acts, to store details of PAN card, Aadhar card,
          Passport, Driving Licence and any other documents/ information
          relating KYC. RELATIONSHIP, NOTICE AND SEVERABLITY None of the
          provisions of the User Agreement shall be deemed to constitute a
          partnership or agency between you and SEC2HAND and you shall have no
          authority to bind SEC2HAND in any manner whatsoever. Except as
          explicitly stated otherwise, any notices shall be given by registered
          postal mail on behalf of SEC2HAND to SEC2HANDBUSINESS SOLUTIONS PVT.
          LTD Attn: Legal Department, at SEC2HANDBUSINESS SOLUTIONS PVT. LTD,
          Plot no. 46, Parihar Nagar, Bhadwasiya, Jodhpur, Rajasthan, India
          342007 (in the case of SEC 2 HAND BUSINESS SOLUTIONS PVT. LTD) or to
          the email address you provide to us during the registration process
          (in your case). Notice shall be deemed given 24 hours after email is
          sent, unless the sending party is notified that the email address is
          invalid. Alternatively, we may give you notice by certified mail,
          postage prepaid and return receipt requested, to the address provided
          to us during the registration process. In such case, notice shall be
          deemed given 3 days after the date of mailing. If any clause of the
          User Agreement shall be deemed invalid, void or for any reason
          unenforceable, such clause shall be deemed severable and shall not
          affect the validity and enforceability of the remaining clauses of the
          User Agreement. ARBITRATION If any dispute arises between you and
          SEC2HAND during your use of the Website or thereafter, in connection
          with the validity, interpretation, implementation or alleged breach of
          any provision of the User Agreement and Seller Terms and Conditions or
          the documents they incorporates by reference, the dispute shall be
          referred to a sole Arbitrator who shall be an independent and neutral
          third party identified by SEC2HAND. The place of arbitration shall be
          Jodhpur, Rajasthan. The Arbitration & Conciliation Act, 1996, shall
          govern the arbitration proceedings. The arbitration proceedings shall
          be in the English language and each party shall pay their own costs
          GOVERNING LAW The User Agreement Terms and Conditions or the documents
          they incorporates by reference shall be governed and construed in
          accordance with the laws of India. ENTIRE AGREEMENT Unless otherwise
          specified herein, the Agreement constitutes the entire agreement
          between the User and the Website/Mobile Application and it supersedes
          all prior or contemporaneous communications and proposals, whether
          electronic, oral or written, between the User and the Website/Mobile
          Application. A printed version of this Agreement and of any notice
          given in electronic form shall be admissible in judicial or
          administrative proceedings based upon or relating to this Agreement to
          the same extent and subject to the same conditions as other business
          documents and records originally generated and maintained in printed
          form.
        </div>
      </div>
    );
  }
}

export default DealerPolicy;
